### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Gabrieleirbag1** [atinfinity/carla_ros_bridge_docker#11]
I can't build the image because it cannot locate the package of carla-simulator.
Thank you for your help !

It did this :
`sudo docker build -t carla:0.9.11 --build-arg GID=$(id -g) --build-arg UID=$(id -u) -f Dockerfile.melodic .`

then this :
```
34.21 E: Unable to locate package carla-simulator
------
Dockerfile.melodic:64
--------------------
  63 |     RUN add-apt-repository "deb [arch=amd64] http://dist.carla.org/carla $(lsb_release -sc) main"
  64 | >>> RUN apt-get update && apt-get install -y --no-install-recommends \
  65 | >>>     carla-simulator=${CARLA_VERSION} \
  66 | >>>     && \
  67 | >>>     apt-get clean && \
  68 | >>>     rm -rf /var/lib/apt/lists/*
  69 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     carla-simulator=${CARLA_VERSION}     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

```

**Comment by atinfinity** [comment]
@Gabrieleirbag1 I could reproduce. And, I found this message.
So, I guess that distribution server stopped.

```
W: Failed to fetch http://dist.carla.org/carla/dists/bionic/InRelease  Could not connect to dist.carla.org:80 (34.227.255.250), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Gabrieleirbag1** [comment]
@atinfinity Thank you for your reply. Do you have any alternative ideas that could work?

**Comment by atinfinity** [comment]
@Gabrieleirbag1 I tried to fix in <https://github.com/atinfinity/carla_ros_bridge_docker/pull/12>. Please check.

**Comment by Gabrieleirbag1** [comment]
Hello, it works, thank you !
![Screenshot from 2024-04-11 09-33-23](https://github.com/atinfinity/carla_ros_bridge_docker/assets/119498688/36b65179-f495-4140-bb3c-800597bcc237)
